spring.application.name=oauth2-demo
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/eazybank/protocol/openid-connect/certs

spring.security.oauth2.resourceserver.opaquetoken.introspection-uri=http://localhost:8180/realms/eazybank/protocol/openid-connect/token/introspect
spring.security.oauth2.resourceserver.opaquetoken.client-id=eazyBankResource
spring.security.oauth2.resourceserver.opaquetoken.client-secret=dWpkaYoxp9hobG33vRypGpqsNulEyTmP